import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "var(--md-sys-color-primary)",
        "on-primary": "var(--md-sys-color-on-primary)",
        "primary-container": "var(--md-sys-color-primary-container)",
        "on-primary-container": "var(--md-sys-color-on-primary-container)",
        secondary: "var(--md-sys-color-secondary)",
        "on-secondary": "var(--md-sys-color-on-secondary)",
        "secondary-container": "var(--md-sys-color-secondary-container)",
        "on-secondary-container": "var(--md-sys-color-on-secondary-container)",
        tertiary: "var(--md-sys-color-tertiary)",
        "on-tertiary": "var(--md-sys-color-on-tertiary)",
        "tertiary-container": "var(--md-sys-color-tertiary-container)",
        "on-tertiary-container": "var(--md-sys-color-on-tertiary-container)",
        error: "var(--md-sys-color-error)",
        "on-error": "var(--md-sys-color-on-error)",
        "error-container": "var(--md-sys-color-error-container)",
        "on-error-container": "var(--md-sys-color-on-error-container)",
        background: "var(--md-sys-color-background)",
        "on-background": "var(--md-sys-color-on-background)",
        surface: "var(--md-sys-color-surface)",
        "on-surface": "var(--md-sys-color-on-surface)",
        "surface-variant": "var(--md-sys-color-surface-variant)",
        "on-surface-variant": "var(--md-sys-color-on-surface-variant)",
        outline: "var(--md-sys-color-outline)",
        "outline-variant": "var(--md-sys-color-outline-variant)",
        neutral: "var(--md-sys-color-neutral)",
        "neutral-variant": "var(--md-sys-color-neutral-variant)",
      },
      fontFamily: {
        sans: ["var(--font-google-sans)", "sans-serif"],
        mono: ["var(--font-roboto-mono)", "monospace"],
      },
      fontSize: {
        "display-large": ["57px", { lineHeight: "64px", letterSpacing: "-0.25px", fontWeight: "400" }],
        "display-medium": ["45px", { lineHeight: "52px", letterSpacing: "0px", fontWeight: "400" }],
        "display-small": ["36px", { lineHeight: "44px", letterSpacing: "0px", fontWeight: "400" }],
        "headline-large": ["32px", { lineHeight: "40px", letterSpacing: "0px", fontWeight: "400" }],
        "headline-medium": ["28px", { lineHeight: "36px", letterSpacing: "0px", fontWeight: "400" }],
        "headline-small": ["24px", { lineHeight: "32px", letterSpacing: "0px", fontWeight: "400" }],
        "title-large": ["22px", { lineHeight: "28px", letterSpacing: "0px", fontWeight: "400" }],
        "title-medium": ["16px", { lineHeight: "24px", letterSpacing: "0.15px", fontWeight: "500" }],
        "title-small": ["14px", { lineHeight: "20px", letterSpacing: "0.1px", fontWeight: "500" }],
        "body-large": ["16px", { lineHeight: "24px", letterSpacing: "0.5px", fontWeight: "400" }],
        "body-medium": ["14px", { lineHeight: "20px", letterSpacing: "0.25px", fontWeight: "400" }],
        "body-small": ["12px", { lineHeight: "16px", letterSpacing: "0.4px", fontWeight: "400" }],
        "label-large": ["14px", { lineHeight: "20px", letterSpacing: "0.1px", fontWeight: "500" }],
        "label-medium": ["12px", { lineHeight: "16px", letterSpacing: "0.5px", fontWeight: "500" }],
        "label-small": ["11px", { lineHeight: "16px", letterSpacing: "0.5px", fontWeight: "500" }],
      },
      boxShadow: {
        "elevation-1": "0px 1px 2px 0px rgba(0,0,0,0.3), 0px 1px 3px 1px rgba(0,0,0,0.15)",
        "elevation-2": "0px 1px 2px 0px rgba(0,0,0,0.3), 0px 2px 6px 2px rgba(0,0,0,0.15)",
        "elevation-3": "0px 1px 3px 0px rgba(0,0,0,0.3), 0px 4px 8px 3px rgba(0,0,0,0.15)",
        "elevation-4": "0px 2px 3px 0px rgba(0,0,0,0.3), 0px 6px 10px 4px rgba(0,0,0,0.15)",
        "elevation-5": "0px 4px 4px 0px rgba(0,0,0,0.3), 0px 8px 12px 6px rgba(0,0,0,0.15)",
      },
      transitionTimingFunction: {
        "emphasized": "var(--md-sys-motion-easing-emphasized)",
        "emphasized-accelerate": "var(--md-sys-motion-easing-emphasized-accelerate)",
        "emphasized-decelerate": "var(--md-sys-motion-easing-emphasized-decelerate)",
      },
      keyframes: {
        "material-enter": {
          "0%": { opacity: "0", transform: "scale(0.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "material-exit": {
          "0%": { opacity: "1", transform: "scale(1)" },
          "100%": { opacity: "0", transform: "scale(0.9)" },
        },
        ripple: {
          "0%": { transform: "scale(0)", opacity: "0.2" },
          "100%": { transform: "scale(4)", opacity: "0" },
        },
      },
      animation: {
        "material-enter": "material-enter 200ms cubic-bezier(0.0, 0.0, 0.2, 1)",
        "material-exit": "material-exit 150ms cubic-bezier(0.4, 0.0, 1, 1)",
        ripple: "ripple 600ms linear",
      },
    },
  },
  plugins: [],
};
export default config;
