export const theme = {
    colors: {
        light: {
            primary: '#0060a7',
            onPrimary: '#ffffff',
            primaryContainer: '#d3e4ff',
            onPrimaryContainer: '#001c3b',
            secondary: '#535f70',
            onSecondary: '#ffffff',
            secondaryContainer: '#d7e3f7',
            onSecondaryContainer: '#101c2b',
            tertiary: '#6b5778',
            onTertiary: '#ffffff',
            tertiaryContainer: '#f2daff',
            onTertiaryContainer: '#251431',
            error: '#ba1a1a',
            onError: '#ffffff',
            errorContainer: '#ffdad6',
            onErrorContainer: '#410002',
            background: '#fdfcff',
            onBackground: '#1a1c1e',
            surface: '#fdfcff',
            onSurface: '#1a1c1e',
            surfaceVariant: '#dfe2eb',
            onSurfaceVariant: '#43474e',
            outline: '#73777f',
            outlineVariant: '#c3c7cf',
            neutral: '#5d5f64',
            neutralVariant: '#5c5f66',
        },
        dark: {
            primary: '#a3c9ff',
            onPrimary: '#00315b',
            primaryContainer: '#004880',
            onPrimaryContainer: '#d3e4ff',
            secondary: '#bbc7db',
            onSecondary: '#253140',
            secondaryContainer: '#3b4858',
            onSecondaryContainer: '#d7e3f7',
            tertiary: '#d7bee4',
            onTertiary: '#3b2947',
            tertiaryContainer: '#533f5f',
            onTertiaryContainer: '#f2daff',
            error: '#ffb4ab',
            onError: '#690005',
            errorContainer: '#93000a',
            onErrorContainer: '#ffdad6',
            background: '#1a1c1e',
            onBackground: '#e2e2e6',
            surface: '#1a1c1e',
            onSurface: '#e2e2e6',
            surfaceVariant: '#43474e',
            onSurfaceVariant: '#c3c7cf',
            outline: '#8d9199',
            outlineVariant: '#43474e',
            neutral: '#909196',
            neutralVariant: '#8f9199',
        },
    },
    typography: {
        display: {
            large: {
                fontFamily: 'Google Sans',
                weight: '400',
                size: '57px',
                lineHeight: '64px',
                tracking: '-0.25px',
            },
            medium: {
                fontFamily: 'Google Sans',
                weight: '400',
                size: '45px',
                lineHeight: '52px',
                tracking: '0px',
            },
            small: {
                fontFamily: 'Google Sans',
                weight: '400',
                size: '36px',
                lineHeight: '44px',
                tracking: '0px',
            },
        },
        headline: {
            large: {
                fontFamily: 'Google Sans',
                weight: '400',
                size: '32px',
                lineHeight: '40px',
                tracking: '0px',
            },
            medium: {
                fontFamily: 'Google Sans',
                weight: '400',
                size: '28px',
                lineHeight: '36px',
                tracking: '0px',
            },
            small: {
                fontFamily: 'Google Sans',
                weight: '400',
                size: '24px',
                lineHeight: '32px',
                tracking: '0px',
            },
        },
        body: {
            large: {
                fontFamily: 'Google Sans',
                weight: '400',
                size: '16px',
                lineHeight: '24px',
                tracking: '0.5px',
            },
            medium: {
                fontFamily: 'Google Sans',
                weight: '400',
                size: '14px',
                lineHeight: '20px',
                tracking: '0.25px',
            },
            small: {
                fontFamily: 'Google Sans',
                weight: '400',
                size: '12px',
                lineHeight: '16px',
                tracking: '0.4px',
            },
        },
    },
    elevation: {
        level0: '0px 0px 0px 0px',
        level1: '0px 1px 2px 0px rgba(0,0,0,0.3), 0px 1px 3px 1px rgba(0,0,0,0.15)',
        level2: '0px 1px 2px 0px rgba(0,0,0,0.3), 0px 2px 6px 2px rgba(0,0,0,0.15)',
        level3: '0px 1px 3px 0px rgba(0,0,0,0.3), 0px 4px 8px 3px rgba(0,0,0,0.15)',
        level4: '0px 2px 3px 0px rgba(0,0,0,0.3), 0px 6px 10px 4px rgba(0,0,0,0.15)',
        level5: '0px 4px 4px 0px rgba(0,0,0,0.3), 0px 8px 12px 6px rgba(0,0,0,0.15)',
    },
};

export type Theme = typeof theme;
